### PR TITLE
Keithley

### PR DESCRIPTION
**Pull request by Chrede88**
New Keithley driver

### CODE REVIEW

**Comment by nikhartman** [comment]
Let's add whatever functions are necessary to make this back-compatible with the old version. We can throw them in at the end and wrap the new functions.

**Comment by nikhartman** [comment]
I can even take care of it. Just not right at this minute.

**Comment by Chrede88** [comment]
Sure, why not. I can look at it tomorrow!

**Comment by Chrede88** [comment]
The old functions should now work as well!

**Comment by nikhartman** [comment]
Cool. We should add a usage example to 'measurement_template.ipf'.

**Pull request merged**
