### PR TITLE
new master branch

### PR DESCRIPTION
**Pull request by nikhartman**
big changes:

1. Allow instruments to be read asynchronously
2. Only support saving data in `hdf5` format
3. More uniform structure of instrument drivers

```
    // xxx_driver.ipf
    function openXXXconnection(...)

    getXXXsomething(...)

    setXXXsomething(...)

    getXXXstatus(...)
```

Really a huge amount of stuff. Probably not worth looking at it all. I've been running this branch for a few weeks and it works great. Just fixed the remaining issues a minute ago.

### CODE REVIEW

**Comment by nikhartman** [comment]
@Chrede88 I don't even know where to start with this mess.

**Comment by Chrede88** [comment]
Well, if you say it works. Let's just merge.
What have you done to the lakeshore driver?

**Comment by Chrede88** [comment]
It seems that you have removed InstrID completely..?

**Comment by nikhartman** [comment]
Which Lakeshore driver? Magnets or temperature?

**Comment by Chrede88** [comment]
Temperature. That’s the only conflict.

**Comment by nikhartman** [comment]
Still works the same way. I did comment out all the GUI functions though.

**Comment by nikhartman** [comment]
I think I fixed it. I'll let you do the honors of murdering this ancient `master` branch. @Chrede88

**Pull request merged**
