### PR TITLE
Added support for more "lose" syntax in calculations scripts

### PR DESCRIPTION
**Pull request by Chrede88**
Calculation scripts does no longer need “[i]”, the code will add them
where needed.

### CODE REVIEW

**Comment by nikhartman** [comment]
Is it possible to only call `construct_calc_script` once, in InitWaves?

**Comment by Chrede88** [comment]
Yes, totally possible. Good idea:)

**Comment by Chrede88** [comment]
I've moved the function call to InitWaves()

**Comment by Chrede88** [comment]
@nikhartman can we sign off on this! I need these changes in the multithread branch.

**Pull request merged**
