### PR TITLE
New JSON

### PR DESCRIPTION
**Pull request by Chrede88**
So many changes..!

### CODE REVIEW

**Comment by nikhartman** [comment]
Why remove the format options from `addJSONkeyvaluepair`?

**Comment by Chrede88** [comment]
I didn't see the need for all that extra stuff. `num2str` is correct to five digits.

**Comment by nikhartman** [comment]
I'm going to merge everything.

**Comment by nikhartman** [comment]
Unless you stop me in like two minutes.

**Comment by Chrede88** [comment]
Go ahead!

**Pull request merged**
